### ISSUE TITLE
Quick Sort in Java

### ISSUE THREAD

**Issue by YourOwnItsMeDHC** [Midway91/HactoberFest2023#100]

**Comment by YourOwnItsMeDHC** [comment]
I would like to contribute Quick Sort algorithm in Java.

Please assign me this issue @Midway91.

**Comment by asharful07** [comment]
allow me to contribute.

**Comment by Harshsaini001** [comment]
@Midway91  Please assign me this issue.
I would like to contribute Quick Sort algorithm in Java.

**Comment by K-Saniya** [comment]
Hello @Midway91 ! I am interested in contributing the Quick sort algorithm in Java . Please assign me with this issue.

**Comment by hecker8055** [comment]
I would like to contribute Quick Sort algorithm in Java.

Please assign me this issue @Midway91.
