### ISSUE TITLE
Find the Longest Increasing Subsequence (LIS)

### ISSUE THREAD

**Issue by vishwajeetfate** [Midway91/HactoberFest2023#1034]
hi @Midway91,   I want to contribute to this repository. 
Problem: Find the Longest Increasing Subsequence (LIS)
 Given an unsorted array of integers, find the length of the longest increasing subsequence. An increasing subsequence is a subsequence in which the elements are in increasing order, but not necessarily contiguous in C++. please assign this issue to me under haktoberfest label.

**Comment by divya1515** [comment]
Please assign this issue to me
