### ISSUE TITLE
Adding Merge Sort (hacktoberfest2023)

### ISSUE THREAD

**Issue by bugzzz4u** [Midway91/HactoberFest2023#1046]
I want to add merge sort in this repo. Please assign me this issue under hacktoberfest label

**Comment by Deeparawat** [comment]
Hey! please assign this to me i can code it  in cpp

**Comment by hecker8055** [comment]
hey @Midway91  assign this task to me

**Comment by bugzzz4u** [comment]
@Midway91  Please assign this task to me asap because I have opened this issue

**Comment by Deeparawat** [comment]
hey ! I have added to code please Accept my pull request #1046
