### ISSUE TITLE
Binary Search in Python

### ISSUE THREAD

**Issue by pr1shaaa** [Midway91/HactoberFest2023#105]
Hi @Midway91 - - I would like to add a Binary Search algorithm in Python. Please assign it to me.

**Comment by aditya-bagla** [comment]
Hi @Midway91 - - I would like to add a Binary Search algorithm in Python. Please assign it to me.

HACTOBERFEST2023

**Comment by MoHiTKuKrEjA11** [comment]
Hey can you please assign this to me with hactoberfest-tag..

**Comment by SakshamSharma07** [comment]
I have created a pull request with binary_search.py with commented explaination.
@Midway91
Please assign it to me.

**Comment by Shiwani5** [comment]
Hi, I Hope you are doing well. This is my first contribution to an open challenge contribution platform. I know the solution to this please assign this to me so that I can contribute.

**Comment by priy-anka17** [comment]
i would like to do binary search in python as i am experienced in python and solved a lot of problems . Please assigned to to me sir @Midway91

**Comment by priy-anka17** [comment]
i would like to do binary search in python as i am experienced in python and solved a lot of problems . Please assigned to to me sir @Midway91
