### ISSUE TITLE
Binary Exponentiation

### ISSUE THREAD

**Issue by AshwinSriram11** [Midway91/HactoberFest2023#1069]
I want to add binary exponentiation algorithm to this repository. Please assign me this issue under the hacktoberfest label.

**Comment by byaswanthk** [comment]
#include <bits/stdc++.h>
using namespace std;
#define ll long long
const ll N = 1e5;
ll fact[N+1];
ll modinv[N+1];
int mod = 1e9+7;
// Mod inverse
ll power(ll base,ll pow)
{
    if(pow<0) return 0;
    ll ans = 1;
    while(pow)
    {
        if(pow%2==0)
        {
            base = (base*base)%mod;
            pow/=2;
        }
        else{
            ans = (ans*base)%mod;
            pow-=1;
        }
    }
    return ans;
}
int main()
{
     ll ans = power(2,12);
     cout<<ans;
}

**Comment by Vikas9kumargupta** [comment]
Hey @Midway91 Assign this task to me

**Comment by Tanisha1421** [comment]
please assign this to me
