### ISSUE TITLE
Adding Quick sort program  hacktoberfest-2023  

### ISSUE THREAD

**Issue by Deeparawat** [Midway91/HactoberFest2023#1082]
Hey please assign this to me . I want to contribute this program

**Comment by hecker8055** [comment]
@Midway91 assign me this

**Comment by Deeparawat** [comment]
Hey ! I have added to code please Accept my pull request #1082

**Comment by Harshsaini001** [comment]
Hey @Midway91 I want to work on this issue under hacktoberfest . Please assing it to me.

**Comment by devyani277** [comment]
Hey,please assign this to me

**Comment by kashyapanjali** [comment]
hii, I want to contribute in this code please assign me and accept my pr

**Comment by divya1515** [comment]
Please assign this issue to me

**Comment by Vikas9kumargupta** [comment]
hey @Midway91 Assign this task to me

**Comment by Tanisha1421** [comment]
please assign this to me
