### ISSUE TITLE
Adding ATM Transaction program hacktoberfest-2023

### ISSUE THREAD

**Issue by gaurav9117** [Midway91/HactoberFest2023#1122]
Hey please assign this to me . I want to contribute this program

**Comment by gaurav9117** [comment]
Hey please assign this to me . I want to contribute this program

**Comment by TusharRastogi04** [comment]
@Midway91 please assign this issue to me sir

**Comment by TusharRastogi04** [comment]
also add hacktoberfest accepted label to this issue

**Comment by gaurav9117** [comment]
successfully merged a pull request.
https://github.com/Midway91/HactoberFest2023/pull/1128
