### ISSUE TITLE
How to find Shortest Paths from Source to all Vertices using Dijkstra’s Algorithm

### ISSUE THREAD

**Issue by Pranavtej** [Midway91/HactoberFest2023#1193]

**Comment by Tanisha1421** [comment]
please assign this to me?

**Comment by shubhdevv** [comment]
hey @Pranavtej ,can you please assign this to me

**Comment by shubhdevv** [comment]
@Midway91 i merged a pull request regarding the same can you please check

**Comment by divya1515** [comment]
Please assign this issue to me

**Comment by Tanisha1421** [comment]
Please merge the pull request
