### ISSUE TITLE
A program in cpp using stl to find permutations of all numbers in array

### ISSUE THREAD

**Issue by DevJSter** [Midway91/HactoberFest2023#1203]
Given an array, the task is to print or display all the permutations of this array using STL in C++. 
Examples:
Input: a[] = {1, 2, 3}
Output:
1  2  3  
1  3  2  
2  1  3  
2  3  1  
3  1  2  
3  2  1  

Input: a[] = {10, 20, 30, 40}
Output:
10  20  30  40  
10  20  40  30  
10  30  20  40  
10  30  40  20  
10  40  20  30  
10  40  30  20  
20  10  30  40  
20  10  40  30  
20  30  10  40  
20  30  40  10  
20  40  10  30  
20  40  30  10  
30  10  20  40  
30  10  40  20  
30  20  10  40  
30  20  40  10  
30  40  10  20  
30  40  20  10  
40  10  20  30  
40  10  30  20  
40  20  10  30  
40  20  30  10  
40  30  10  20  
40  30  20  10

**Comment by DevJSter** [comment]
Hey there @Midway91 Please assign me this issue and add the labels too

**Comment by shubhdevv** [comment]
hey @Midway91 ,can you please assign this to me

**Comment by DevJSter** [comment]
Bro I've already done and created the pr .... I can create another issue and you contribute on that would you???

**Comment by DevJSter** [comment]
@shubhdevv fine?

**Comment by shubhdevv** [comment]
sure @DevJSter

**Comment by shubhdevv** [comment]
did your pr got accepted in the hactoberfest though?

**Comment by DevJSter** [comment]
No still not

**Comment by shubhdevv** [comment]
@DevJSter done now right?

**Comment by DevJSter** [comment]
Hey @Midway91 you did not added the labels bro while merging please add the labels yo!!!

**Comment by DevJSter** [comment]
@Midway91 bro you haven't addded the labels
