### ISSUE TITLE
Priority Queue in C++ Standard Template Library (STL)

### ISSUE THREAD

**Issue by DevJSter** [Midway91/HactoberFest2023#1206]

**Comment by DevJSter** [comment]
Hey @Midway91 Kindly look at PR and add the labels as ive solved this issue

**Comment by divya1515** [comment]
Please assign this issue to me

**Comment by DevJSter** [comment]
hey @divya1515  I've solved this issue!!

**Comment by DevJSter** [comment]
@Midway91  bro where's the label?
