### ISSUE TITLE
Power of a number using Recursion in Python

### ISSUE THREAD

**Issue by suburban-daredevil** [Midway91/HactoberFest2023#125]
Hi @Midway91 

I would like to contribute Python based implementation of Power of Number using Recursion. It would be great if you could assign this issue to me :)

### Explanation:
Given two numbers, x and n, print the result of "x raised to the power of n" using recursion. The language of implementation is Python.

Thanks

**Comment by suburban-daredevil** [comment]
This [PR](https://github.com/Midway91/HactoberFest2023/pull/132) closes this issue.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.
