### ISSUE TITLE
SubSetSum equal to K

### ISSUE THREAD

**Issue by LakshmanGamers** [Midway91/HactoberFest2023#128]
I want to Contribute this in java dynamic programming section.

**Comment by MoHiTKuKrEjA11** [comment]
Hey can you please assign this to me with hactoberfest-tag..

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by princikarai** [comment]
Please assign this issue to me. I am capable of providing a brute force solution to most optimize solution with time and space complexity mentioned.And will also add comment wherever needed.Will make code most optimized and user friendly.
I'm good in DSA and Pproblem Solving.
Thank You

**Comment by Sakshipakhale11** [comment]
Hello,I would like to work on this issue. Can you please assign it to me?
