### ISSUE TITLE
Want to add a program making use of function overloading in C++ to find the area of rectangle.

### ISSUE THREAD

**Issue by LeViiAcKerMan01** [Midway91/HactoberFest2023#1355]

**Comment by Midway91** [comment]
@LeViiAcKerMan01 Hacktoberfest is over

**Comment by LeViiAcKerMan01** [comment]
> @LeViiAcKerMan01 Hacktoberfest is over

Sorry bud I still wanna live in October only , NNN is not a gud thing!

**Comment by LeViiAcKerMan01** [comment]
> @LeViiAcKerMan01 Hacktoberfest is over

**Comment by Midway91** [comment]
@LeViiAcKerMan01 You can still contribute you just can't have the label
