### ISSUE TITLE
N-Queens Problem using backtracking in JAVA

### ISSUE THREAD

**Issue by Rishab-Kumar-R** [Midway91/HactoberFest2023#162]
Hey @Midway91 can you assign this to me, I am new to open-source contributions and need to get my hands on to this.

**Comment by Rishab-Kumar-R** [comment]
Hey @Midway91 can you please assign this to me

**Comment by MoHiTKuKrEjA11** [comment]
Hey can you please assign this to me with hactoberfest-tag..

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.
