### ISSUE TITLE
Excluded from Hactoberfest 2023

### ISSUE THREAD

**Issue by suburban-daredevil** [Midway91/HactoberFest2023#166]
This repository has been excluded from Hacktoberfest 2023. So, even if your PR is merged, it will only be reflected in the excluded section of the Hacktoberfest 2023 webpage and not be counted towards the overall progress section.

**Comment by mahammadhussain98** [comment]
Hello @

> This repository has been excluded from Hacktoberfest 2023. So, even if your PR is merged, it will only be reflected in the excluded section of the Hacktoberfest 2023 webpage and not be counted towards the overall progress section.

Hello,can you please suggest me any best repository for hactoberfest 2023 with these tech stack:html,css,js,cpp,python

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.
