### ISSUE TITLE
shell sort implementation using C++

### ISSUE THREAD

**Issue by ujjwalbhandarii** [Midway91/HactoberFest2023#172]
Shell sort is the crucial sorting algorithm for understanding the concept of data structure and other sorting algorithms. I wanted to add shell sort using C++ in this repo as this will add value for the repo viewers for understanding the full concepts of it.

@Midway91 please assign me🌝.

**Comment by ujjwalbhandarii** [comment]
@Midway91 assign me🌝🚀.

**Comment by kashyapanjali** [comment]
can I change in this particular algorithm

**Comment by Sam654123** [comment]
i would like to contribute in it

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by SatsNik** [comment]
please assign it to me
