### ISSUE TITLE
Huffman Coding Compression Algorithm 

### ISSUE THREAD

**Issue by Pratik-1302** [Midway91/HactoberFest2023#176]
Huffman coding (also known as Huffman Encoding) is an algorithm for doing data compression, and it forms the basic idea behind file compression. The method which is used to construct optimal prefix code is called Huffman coding.
This algorithm builds a tree in bottom up manner.

 I wanted to add Huffman Coding Compression Algorithm using C++ in this repo as this will add value for the repo viewers for understanding the full concepts of it. ⚡

@Midway91 Please Assign me 🙂.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by Pratik-1302** [comment]
can you add hacktoberfest label on it , so it will count in Hacktoberfest

**Comment by Pratik-1302** [comment]
My code is already merge , does it will count in Hacktoberfest
