### ISSUE TITLE
Sorting & Searching Algorithms in java

### ISSUE THREAD

**Issue by DevDatir** [Midway91/HactoberFest2023#208]
Hello, I would like to add searching and sorting algorithms in Java language 
can I work on this issue @Midway91

**Comment by Harshsaini001** [comment]
Hello @Midway91 , I would like to add searching and sorting algorithms in Java language
can I work on this issue.

**Comment by SakshamSharma07** [comment]
Hello @Midway91 , I would like to add searching and sorting algorithms in Java language
can I work on this issue?

**Comment by K-Saniya** [comment]
Hello @Midway91 , I am interested to contribute in this by adding sort and search algorithms in Java language. Can I work on this?
