### ISSUE TITLE
Random Quote Generator made with JavaScript

### ISSUE THREAD

**Issue by Purvesh77** [Midway91/HactoberFest2023#239]

**Comment by Purvesh77** [comment]
Hello @Midway91 ! I'd like to add Random Quote Generator made with JavaScript , can you please assign me this under hacktoberfest 2023 ?

**Comment by parthivghose2919** [comment]
Heyy @Midway91 Can you assign me also in this project I have started working on this project and lmost made a simple Random quote generator.ThankYou!!!

**Comment by tanayduddalwar** [comment]
Hello Sir,can you assign me this issue.I want to work on this issue
