### ISSUE TITLE
Text to Speech Converter

### ISSUE THREAD

**Issue by ritikalath30** [Midway91/HactoberFest2023#31]
Hey, @Midway91 i would like to work on this. Can you please assign it to me?

**Comment by Prasun09** [comment]
Currently in collage  i would like to work with you

**Comment by Midway91** [comment]
@ritikalath30 would you be willing to work with Prasun09

**Comment by Prasun09** [comment]
yes i want to work with you

**Comment by Midway91** [comment]
@Prasun09 @AnushkJain2201 you guys are both assigned

**Comment by Prasun09** [comment]
Awesome, thank you so much!
but what i have to do ??..

**Comment by Midway91** [comment]
@Prasun09 I don't know you will have to communicate with @AnushkJain2201

**Comment by ritikalath30** [comment]
@Midway91 i wish to do this alone

**Comment by Prasun09** [comment]
but why i can also contribute

**Comment by ritikalath30** [comment]
@Prasun09 It is nothing personal; the project won't require the involvement of two people hence i insisted on working alone on it. We can collaborate on another project. Does that sound cool?

**Comment by ritikalath30** [comment]
@Midway91 I do not have permission to push my code. Can you please check

**Comment by ashfaque-mustaque** [comment]
i want to do this can you assign me

**Comment by ashfaque-mustaque** [comment]
Hey, @Midway91 i would like to work on this. Can you please assign it to me?

**Comment by Midway91** [comment]
@Midway91 I don't know how to check.

**Comment by Prasun09** [comment]
Ok, no problem.

**Comment by ritikalath30** [comment]
@Midway91 how will i push my code? i am getting 403 error means forbidden
