### ISSUE TITLE
Organize the files

### ISSUE THREAD

**Issue by Midway91** [Midway91/HactoberFest2023#314]
Can I have someone organize all of the files into their correct folders. All of the folders should be in the Hacktoberfest folder. If there isn't a correct folder for the programming language make a folder with the name of the language.

**Comment by khalid586** [comment]
Okay . I will do that .. assign me this with hacktoberfest 2023 label.

**Comment by Midway91** [comment]
@khalid586 How is it coming along.

**Comment by Nikunjpatel2411** [comment]
Hello
could you please assign me this issue under #hacktoberfest2023
I will try my best...

**Comment by garvpatidar04** [comment]
Hey! @Midway91 Can you assign me this I would like to Contribute.

**Comment by ankitkumar748846** [comment]
@Midway91 Please assign me this

**Comment by udgirkarambarish** [comment]
Hey I would like to contribute and organize. Please assign me :)

**Comment by garvpatidar04** [comment]
Hey @Midway91 Can you please check my PR ( #538  )and validate it, is it good for hacktoberfest-accepted label or not.

**Comment by priyanka0921** [comment]
Hey @Midway91  can you  assign me ? so, that I can contribute the code in Hacktoberfest 2023 , where you can arrange your folders with the  programming language !!

**Comment by om-bhandari-29** [comment]
Hey @Midway91 I would like to contribute to this issue. Please assign this to me. Also add hacktoberfest-accepted label :)

**Comment by bhumikagajrani** [comment]
Hey @Midway91 I would like to contribute to this issue. Please assign this to me.

**Comment by itssiddhantjain** [comment]
> Hey! @Midway91 Can you assign me this I would like to Contribute.

No you can not.

**Comment by a0s21en5** [comment]
Hey @Midway91, Please assign this to me, I would like to contribute to this issue.
