### ISSUE TITLE
i want to add matrix multiplication program to the repo.

### ISSUE THREAD

**Issue by ak3255** [Midway91/HactoberFest2023#329]

**Comment by Ishika0-0** [comment]
@Midway91 Can I contribute to #329 issue

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by Paragcharlie** [comment]
I wish to contribute to this issue can you assign it to me.

**Comment by Devjyoti03** [comment]
I wish to contribute to this issue. Can you assign this task to me?

**Comment by kmanishprogrammar** [comment]
please assign this to me as i would like to work on it

**Comment by Aman-Agrawal-22** [comment]
i think i can work on it very well

**Comment by Vaishwanavi** [comment]
I can work on this isuue ,please assign me thise issue.
