### ISSUE TITLE
Please make a CONTRIBUTING.md

### ISSUE THREAD

**Issue by gruelingpine185** [Midway91/HactoberFest2023#33]
Beginners may not know how to fork, commit, or perform any other necessary operations to contribute to this project. It's an inconvenience for them to look elsewhere, so please make such a file.

**Comment by Midway91** [comment]
@gruelingpine185 would you be willing to make this file for me as I am new to this whole thing too. If is isn't too much of an inconvenience.

**Comment by gruelingpine185** [comment]
I'll give it a try.

**Comment by Midway91** [comment]
@gruelingpine185 Thank you so much. I can always check it over to see if I think anything is missing.

**Comment by gruelingpine185** [comment]
If you'd like an opportunity to participate, I've also just made a repo: https://github.com/gruelingpine185/hacktoberfest-2023
