### ISSUE TITLE
Matrix Multiplication (PYTHON) [HACTOBERFEST 2023]

### ISSUE THREAD

**Issue by apu52** [Midway91/HactoberFest2023#4]
Hello Sir,
I want to add my **Python codes** in this repo. I want to a very basic problem statement code in this repo

**Problem Statement :** _Write a program to multiply two matrices as nested lists._
I want to add the the solution code to this problem.

Can you please give me a chance to contribute in this repo??

**Comment by apu52** [comment]
@Midway91 Can you please assign me this issue. So that I can work on this issue

**Comment by harshmishra19** [comment]
@Midway91 Please assign me to this issue; I would like to work on it

**Comment by AnushkJain2201** [comment]
Assign It To Me I Will Do It With Full Accuracy.

**Comment by aryan-rohit** [comment]
Hello Sir,
I want to add my C++ codes in this repo. I want to add some standard  c++ questions in this repo

Problem Statement : Write a program to  check valid parenthesis in cpp?
I want to add the the solution code to this problem.

Can you please give me a chance to contribute in this repo??

**Comment by aryan-rohit** [comment]
@Midway91  please assign this issue to me.

**Comment by hitali-khachane** [comment]
Hello Sir,
I want to add my Python codes in this repo. 
Problem Statement : Write a program to multiply two matrices 
I want to add the the solution code to this problem.

Can you please give me a chance to contribute in this repo??

**Comment by SayaliMarathe-13** [comment]
Hello sir,
I kindly request the addition of a BFS (Breadth-First Search in python) problem to the Hacktoberfest repository. I am relatively new to open source and I willing to work on this ....please give me a chance to contribute to this repository.

**Comment by MoHiTKuKrEjA11** [comment]
Hey can you please assign this to me with hactoberfest-tag..

**Comment by kashyapanjali** [comment]
may I change in this code with other process

**Comment by Sakshipakhale11** [comment]
Hello,I would like to work on this issue. Can you please assign it to me?
