### ISSUE TITLE
Book Allocation Problem in cpp

### ISSUE THREAD

**Issue by Shrejal123** [Midway91/HactoberFest2023#409]
I want to contribute Book Allocation Problem. Could you please assign it to me under hactoberfest.

**Comment by Monib007** [comment]
Hey I would like to contribute to this issue. Would you please assign me this task .

**Comment by MENT0Z** [comment]
i wanna work on it  plz assign it to me

**Comment by Shrejal123** [comment]
@Midway91 you are assigning it to me then how you can accept any other contributions please tell me
