### ISSUE TITLE
Create a problem folder 

### ISSUE THREAD

**Issue by Khandelwal05** [Midway91/HactoberFest2023#437]
We can create a dedicated folder within this repository for the purpose of uploading practice questions of the C language. The intention behind this folder will be to provide a valuable resource for users by offering a collection of practice questions that can be benificial in their learning and preparation.

**Comment by Khandelwal05** [comment]
Please assign me #437 under hactoberfest and hactoberfest-accepted label
I'll actively contribute to this repository

**Comment by Bib3k4u** [comment]
Can I work on this??

**Comment by vedali29** [comment]
i would like to do it. will you assign it me.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by udgirkarambarish** [comment]
Hey I would like to contribute. Please assign me this issue with hacktoberfest-accepted label :)

**Comment by urveesh28** [comment]
Hey @Midway91 I would to contribute . Please assign me this issue :)

**Comment by arpitya** [comment]
Hey @Midway91 I would like to contribute. Please assign it me :)
