### ISSUE TITLE
Dynamic Programming Standard Patterns

### ISSUE THREAD

**Issue by aniketkuma-r** [Midway91/HactoberFest2023#44]
Those who cannot remember are condemned to repeat.  ~ DP

I am gonna add Standard DP problems pattern wise in cpp.
1D DP
2D/3D DP (DP on grids)
DP on strings
DP on Subsequences
DP on LIS
MCM DP | Partition DP

**Comment by Aniket3063** [comment]
Hello @Midway91,
I want to add all code one by one into HactoberFest/C++/Dynamic Programming.
please assign it to me.
Thank you.

**Comment by Aniket3063** [comment]
Under Hackltoberfest2023.

**Comment by draksham** [comment]
Hello Sir/Mam,

I want to work on it 
please assign to me.
Thank you

**Comment by mrinalproxy** [comment]
Hello @Midway91 Please assign this issue to me
