### ISSUE TITLE
Add a folder for C#

### ISSUE THREAD

**Issue by Suyog-Kulkarni** [Midway91/HactoberFest2023#479]
Add a new folder for C# and implement Quick Sort and Merge Sort.

**Comment by Suyog-Kulkarni** [comment]
Thank you for your response, will do it as soon as possible.

**Comment by Suyog-Kulkarni** [comment]
Implemented Quick Sort and Merge Sort using C#.

**Comment by Vaishwanavi** [comment]
Add a new folder of C  ,which includes all types of sortings and searchings.please assign me this issue.
