### ISSUE TITLE
Tower of Hanoi problem in Java

### ISSUE THREAD

**Issue by Vishwas2** [Midway91/HactoberFest2023#483]
I want to solve the tower of Hanoi problem in Java. Please assign this to me under hacktoberfest tag.

**Comment by Dev-Abhay01** [comment]
please assign me this problem

**Comment by SaritaMohapatra1975** [comment]
I have solved this already and this shows my experience so would like to do this please assign this to me.

**Comment by aryankshl** [comment]
hey @Vishwas2 can you assign this to me?
