### ISSUE TITLE
I want to implement stack using linked list

### ISSUE THREAD

**Issue by Jyoti040** [Midway91/HactoberFest2023#515]
Please assign this to me under hacktoberfest

**Comment by abhinavn2206146** [comment]
Hello @Midway91 , I can implement stacks using Linked List, Can you assign me this under Hactoberfest

**Comment by abhinavn2206146** [comment]
Thanks for assigning it to me @Midway91, I have created the pull request

**Comment by rehan700** [comment]
Hello @Midway91, please assign this issue to me under HACKTOBERFEST2023

This will be my first issue.

**Comment by sukanyagurav** [comment]
Hello @Midway91 , I can implement stacks using Linked List with JS Could you assign it to me.

**Comment by Shivam-Batham** [comment]
Assign me

**Comment by mansi1309** [comment]
Hello @Midway91  ,Please assign this issue to me under Hacktoberfest2023

**Comment by AdityaKrSingh26** [comment]
Hey  @Midway91 I can fix this issue , Could you please assign me this issue

**Comment by Sudo-Aditi** [comment]
Assign this to me
