### ISSUE TITLE
I want to add code of FourSum problem in Cpp

### ISSUE THREAD

**Issue by ashish5433** [Midway91/HactoberFest2023#521]

**Comment by abhinavn2206146** [comment]
Hello @Midway91 , I can contribute the problem FourSum in C++, Can you assign this to me under the tag hacktober

**Comment by rehan700** [comment]
Hello @Midway91, please assign this issue to me under HACKTOBERFEST2023

This will be my first issue.

**Comment by Shivam-Batham** [comment]
/ Assign me this issue to me under HACKTOBERFEST2023

**Comment by mansi1309** [comment]
Hello @Midway91, can you please assign this issue to me under HACKTOBERFEST2023

This will be my first issue.

**Comment by Divyansh200102** [comment]
i want to work  on this issue please assign to me @Midway91
