### ISSUE TITLE
Java Practise Questions

### ISSUE THREAD

**Issue by urveesh28** [Midway91/HactoberFest2023#627]
We can create a dedicated folder within this Repository , which will consists of different Basic to Advanced Java Questions

**Comment by urveesh28** [comment]
Hey @Midway91 Please assign me this issue . Would love to contribute :)

**Comment by Miraj06** [comment]
please assign me this issue 
#627

**Comment by saseentharan** [comment]
Assign this issue to me @saseentharan

**Comment by devjit485** [comment]
Hey can i get a chance to contribute in this issue?

**Comment by urveesh28** [comment]
# created javaPrograms folder and updated contributors.md

**Comment by urveesh28** [comment]
#698
