### ISSUE TITLE
Diameter of a tree

### ISSUE THREAD

**Issue by Akash7649** [Midway91/HactoberFest2023#651]
Hey, @Midway91 I would like to contribute a program that calculates the diameter of a tree using C++. So please assign me this issue under Hacktoberfest2023

**Comment by AdityaKrSingh26** [comment]
Hey @Midway91 I can write a cpp code to calculate diameter of a tree . Please assign me this issue

**Comment by devjit485** [comment]
Hey, @Midway91 I want contribute to calculates the diameter of a tree using java.  Please assign me this issue under Hacktoberfest2023

**Comment by Kirti-Pant** [comment]
Hey, @Midway91 I want contribute in it using C++. Please assign me this issue under Hacktoberfest2023

**Comment by GNITHINKUMAR** [comment]
hello, @Midway91 I would like to contribute to this issue can you please assign it to me
