### ISSUE TITLE
Largest Sum Contiguous Subarray(Standard DSA question)

### ISSUE THREAD

**Issue by GNITHINKUMAR** [Midway91/HactoberFest2023#736]

**Comment by GNITHINKUMAR** [comment]
Hey, @Midway91 , I would like to contribute a Cpp code for this problem using (Kadanes's Algorithm), I will provide all the three brute, better, optimal solutions for the problem as it is very important for interviews in placements.

**Comment by swarupsahu08** [comment]
Hey @Midway91 ,Please assign this issue to me, I would like to contribute the java code for this problem using Kadane's algorithm,as it is the most important interview question

**Comment by swarupsahu08** [comment]
Hey @Midway91 I have submitted the pull request ,can you approve to merge it
