### ISSUE TITLE
Pattern Problem in C++

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#745]
There is no any pattern problems in cpp, I would like to add few pattern problems such as Diamond Star Pattern, Binary Number Triangle Pattern, Number Crown Pattern, Increasing Number Triangle Pattern, Alpha-Hill Pattern, Alpha-Ramp Pattern, Reverse Letter Triangle Pattern, Alpha-Triangle Pattern, Symmetric-Void Pattern, Symmetric-Butterfly Pattern, The Decreasing Number Pattern and Hollow Rectangle Pattern under c++. 
Hey @Midway91, Please assign it to me, will love to make a valuable contribution in the repo.

**Comment by 51tejalhajari** [comment]
hey can you please assign this issue to me and please add hactoberfest label
