### ISSUE TITLE
Bubble Sort in cpp.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#748]
Hey @Midway91 I would love to contribute to this problem under C++, Please do assign it to me.

**Comment by vermaaarti** [comment]
Hey @Midway91 done, Please check

**Comment by Pritee-gupta-jpg** [comment]
please assign this to me

**Comment by unkown577** [comment]
I want to contribute and solve this issue

**Comment by Zainabohlic** [comment]
Dear @Midway91  
I would like to work on this issue under Hacktoberfest 2023. Could you please assign it to me?
Regards
