### ISSUE TITLE
Find the Largest element in an array in cpp.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#754]
Hey @Midway91 I would love to contribute to this problem under C++, Please do assign it to me.
where the problem statement is :-
Given an array, we have to find the largest element in the array.

**Comment by SanskrutiKulkarni** [comment]
please assign this to me

**Comment by Zainabohlic** [comment]
Dear @Midway91  
I would like to work on this issue under Hacktoberfest 2023. Could you please assign it to me?
Regards
