### ISSUE TITLE
Find Second Smallest and Second Largest Element in an array in Cpp.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#755]
Hey @Midway91 I would love to contribute to this problem under C++, Please do assign it to me.

**Comment by thrustyvector** [comment]
@Midway91 please assign it to me

**Comment by thrustyvector** [comment]
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector<int> arr = {12, 45, 1, 9, 67, 32, 10, 4, 21};
    
    int smallest = INT_MAX; // Initialize to maximum possible value
    int secondSmallest = INT_MAX; // Initialize to maximum possible value
    int largest = INT_MIN; // Initialize to minimum possible value
    int secondLargest = INT_MIN; // Initialize to minimum possible value

    for (int i = 0; i < arr.size(); i++) {
        if (arr[i] < smallest) {
            secondSmallest = smallest;
            smallest = arr[i];
        } else if (arr[i] < secondSmallest && arr[i] != smallest) {
            secondSmallest = arr[i];
        }

        if (arr[i] > largest) {
            secondLargest = largest;
            largest = arr[i];
        } else if (arr[i] > secondLargest && arr[i] != largest) {
            secondLargest = arr[i];
        }
    }

    cout << "Second Smallest: " << secondSmallest << std::endl;
    cout << "Second Largest: " << secondLargest << std::endl;

    return 0;
}

**Comment by Zainabohlic** [comment]
Dear @Midway91  
I would like to work on this issue under Hacktoberfest 2023. Could you please assign it to me?
Regards
