### ISSUE TITLE
Check if an Array is Sorted in Cpp.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#756]
Hey @Midway91 I would love to contribute to this problem under C++, Please do assign it to me.

**Comment by thrustyvector** [comment]
@Midway91 please assign it tome

**Comment by Zainabohlic** [comment]
Dear @Midway91  
I would like to work on this issue under Hacktoberfest 2023. Could you please assign it to me?
Regards

**Comment by 1Amit-singh** [comment]
@Midway91 i have added the program can you assign it to me.
