### ISSUE TITLE
EXCLUDED from Hacktoberfest

### ISSUE THREAD

**Issue by Rahullkumr** [Midway91/HactoberFest2023#77]
# Hacktoberfest website still giving the same status

![uselessrepo](https://github.com/Midway91/HactoberFest2023/assets/42183055/d4756cb2-e718-4afc-a779-6125f57b1947)

**Comment by Midway91** [comment]
@Rahullkumr I don't know why

**Comment by Midway91** [comment]
@Rahullkumr I may have found the problem for the "hacktoberfest-accepted" tag I spelled it wrong

**Comment by Rahullkumr** [comment]
may be
