### ISSUE TITLE
Real Time Timer Project in JavaScript.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#795]
Hey @Midway91, I would like to enhance this repository by adding a small interactive JS project which will work as a timer, please assign it the hacktoberfest label.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by Pritee-gupta-jpg** [comment]
please assign this to me

**Comment by saku1331** [comment]
kindly add hactoberfest accepted label.
