### ISSUE TITLE
Grocery List JS project.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#796]
Hey @Midway91, I would like to enhance this repository by adding an interactive JavaScript project for creating and editing a grocery list, please assign it the hacktoberfest label.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by TanishkAgarwal** [comment]
hey @Midway91 I would like to contribute please assign me also with this project

**Comment by rahulsingh5926** [comment]
i can also contribute in building grocery list please assign me this task

**Comment by saku1331** [comment]
kindly add hactoberfest accepted label.
