### ISSUE TITLE
Validate registration and login form using JavaScript

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#799]
Hey @Midway91, I would like to enhance this repository by adding a Form Validation under javascript, please assign it the hacktoberfest-accepted label.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by Pritee-gupta-jpg** [comment]
please assign this to me

**Comment by TanishkAgarwal** [comment]
hey @Midway91 I would Like you to provide a full functional registration page with all the requirement you want , please assign me this project

**Comment by anindita-panda** [comment]
Hey! I would like to contribute. Please assign me the task.

**Comment by Pritee-gupta-jpg** [comment]
Please merge my PR and kindly add Hactoberfest-accepted label.Thank you.

**Comment by Sakshipakhale11** [comment]
Hello,I would like to work on this issue. Can you please assign it to me?
