### ISSUE TITLE
Number Guessing Game in JS.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#800]
Hey @Midway91, I would like to enhance this repository by adding a number guessing game under javascript, please assign it the hacktoberfest label.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by Pritee-gupta-jpg** [comment]
please assign this to me

**Comment by arjungupta01** [comment]
Hey @Midway91 sir can you please assign me this issue .
Thankyouu!!

**Comment by harsh0728** [comment]
Please assign this to me
