### ISSUE TITLE
Whack-a-mole game in JS.

### ISSUE THREAD

**Issue by vermaaarti** [Midway91/HactoberFest2023#801]
Hey @Midway91, I would like to enhance this repository by adding a Whack-a-mole game under javascript, please assign it the hacktoberfest label.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by TanishkAgarwal** [comment]
I wish I like to contribute to the task please assign me

**Comment by TanishkAgarwal** [comment]
Hi @Midway91, I would like you help you in this project and like to contribute to this project so please assign me with this project

**Comment by saku1331** [comment]
kindly add hactoberfest accepted label.

**Comment by hecker8055** [comment]
hey @Midway91  assign this task to me
