### ISSUE TITLE
Investment Calculator

### ISSUE THREAD

**Issue by rahulkundu1209** [Midway91/HactoberFest2023#820]
I want to add an investment calculator web app, developed in React JS. Please assign me this issue under hacktoberfest tag.

**Comment by Pritee-gupta-jpg** [comment]
please assign it to me

**Comment by Adarsh8999** [comment]
Please assign it to me.

**Comment by priyanka0921** [comment]
@Midway91  can you assign through which i can simply add investment calculator web using js?
