### ISSUE TITLE
rock paper scissor game 

### ISSUE THREAD

**Issue by SHAGNIK007** [Midway91/HactoberFest2023#845]
i want to add a rock paper scissor game made using python.
please assign me this with hacktoberfest label

**Comment by Tanishka-22** [comment]
could you please assign me too over this issue

**Comment by LeViiAcKerMan01** [comment]
Can you assign me too over this issue i want to add rock paper scissor game using c.

**Comment by Midway91** [comment]
@LeViiAcKerMan01 Go for it
