### ISSUE TITLE
Binary Search in java. Please add hacktoberfest label

### ISSUE THREAD

**Issue by Rajiiee** [Midway91/HactoberFest2023#864]

**Comment by vishnugaruda246** [comment]
Hey @Midway91 could assign me on this issue, would like to contribute

**Comment by Harshsaini001** [comment]
@Midway91 Hii , I want to work on this issue. Please, assing me this issue under Hacktoberfest2023.

**Comment by Zainabohlic** [comment]
please assign me this issue
regards

**Comment by Souradeephazra123** [comment]
Please assign this issue to me.

**Comment by RutujaTathod** [comment]
pls assign me

**Comment by vishnugaruda246** [comment]
@Midway91 have a  review

**Comment by vishnugaruda246** [comment]
@Midway91 could you add hacktoberfest labels
