### ISSUE TITLE
Password generator (hacktoberfest 2023)

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Midway91/HactoberFest2023#945]
I would like to contribute in your project by adding a password generator program. Kindly allow me to work on this feature under hacktoberfest 2023

**Comment by Suchitra-Sahoo** [comment]
I have added the program of password generator in the issue #1050 . Kindly review it. After checking please add the hacktoberfest-accepted tag.

**Comment by TanushreeBorase** [comment]
i would like to add code for this @Midway91 under havktoberfest 2023,can u assign me
