### ISSUE TITLE
Rock Paper Scissor game  (hacktoberfest 2023)

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Midway91/HactoberFest2023#946]
I would like to add a rock paper scissor game in your project. Kindly allow me to work on this feature under hacktoberfest 2023.

**Comment by Pritee-gupta-jpg** [comment]
please assign this to me.

**Comment by Suchitra-Sahoo** [comment]
I have added the program of rock paper scissor game. Kindly review it and put hactoberfest-accepted tag.
