### ISSUE TITLE
To-do list generator (hacktoberfest 2023)

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Midway91/HactoberFest2023#947]
I would like to add a To-do list creator in your project. Kindly allow me to work on this feature under hacktoberfest 2023)

**Comment by Deeparawat** [comment]
Hey ! I wanted to add a beautifully designed yet simple to-do list.Kindly allow me to work on this feature under hacktoberfest 2023.

**Comment by Deeparawat** [comment]
Hey ! @Midway91 I have pushed the code please check it !!

**Comment by Shiv10122003** [comment]
hello @Midway91 i would like to work on this issue

**Comment by 24Priyanshi** [comment]
I would be pleased to work on this issue.
