### ISSUE TITLE
N-Queen problem using backtracking in Java. Please add Hactoberfest label

### ISSUE THREAD

**Issue by VivekTiwari-1** [Midway91/HactoberFest2023#956]
I want to add N-Queen problem's solution using backtracking to your repo, please assign me this issue

**Comment by Babuprasanth27** [comment]
Hey, I am interested to solve this issue

**Comment by VivekTiwari-1** [comment]
I have added code of N-Queen's problem in the pull request #1064  . Kindly review it and please add the hacktoberfest-accepted tag.

**Comment by Anjali286** [comment]
Hello @Midway91 
I want to add C++ as well as Python code for the N-queen problem using backtracking so that programmers with these languages can take advantage of your repo.
Please assign me this issue.

**Comment by Vikas9kumargupta** [comment]
Hello @Midway91
I want to add Java code for the N-queen problem using backtracking so that programmers with these languages can take advantage of your repo.
Please assign me this issue.
