### ISSUE TITLE
Sort strings in lexicographical order . Please add HactoberFest label

### ISSUE THREAD

**Issue by VivekTiwari-1** [Midway91/HactoberFest2023#957]
I want to add this in your repo, please assign me this

**Comment by Zainabohlic** [comment]
Please assign me this issue
regards

**Comment by Deeparawat** [comment]
Hey ! I wanted to work on it. Kindly, assign this to me.

**Comment by VivekTiwari-1** [comment]
I have added the code to sort Strings in lexicographical order in the pull request #1067  . Kindly review it and please add the hacktoberfest-accepted tag.

**Comment by Deeparawat** [comment]
Hey ! Done with code edit please review it . Kindly review it .

**Comment by Zainabohlic** [comment]
> Please assign me this issue regards

You have assigned this issue to me but I am unable to access the code, can you please tell how to fix this?
<img width="638" alt="Screenshot 2023-10-23 at 7 12 08 PM" src="https://github.com/Midway91/HactoberFest2023/assets/129050037/f84c2512-31da-4945-8475-d2c8c72130cc">
