### ISSUE TITLE
Linear Search in Python

### ISSUE THREAD

**Issue by pr1shaaa** [Midway91/HactoberFest2023#99]
Hi @Midway91 - I would like to add a Linear Search algorithm in Python. Please assign it to me.

**Comment by MoHiTKuKrEjA11** [comment]
Hey can you please assign this to me with hactoberfest-tag..

**Comment by Jugnu-Gupta** [comment]
@Midway91 please assign this task to me.

**Comment by kmanishprogrammar** [comment]
please assign this to me as i would like to work on it

**Comment by Sakshipakhale11** [comment]
Hello,I would like to work on this issue. Can you please assign it to me?
